version: '3'

services:
  webapp:
    container_name: webapp
    image: registry.sb.upf.edu/tide/teaspilsdash:3.0.1
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn teaspils.wsgi:application --bind 0.0.0.0 --workers 3 --timeout 120
    # entrypoint: [./wait.sh]
    ports:
      - "8000:8000"
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      DJANGO_SETTINGS_MODULE: teaspils.settings
    volumes:
      - .:/teaspils
    # - /tmp/app/mysqld:/run/mysqld
    # depends_on:
      # - mysql
    restart: always

# volumes:
#   mysql-data: