alerts_plantHistory = [{"text":"La temperatura ha augmentat un 8% respecte la setmana passada","icon":"fa-thermometer-three-quarters"},
                    {"text":"La temperatura màxima ha estat 25.8ºC","icon":"fa-thermometer-full"},
                    {"text":"S’han recollit dades cada 35 minuts","icon":"fa-clock"},
                    {"text":"La temperatura màxima ha estat a les 17:20h","icon":"fa-clock"},
                    {"text":"Les temperatures mínimes han estat durant les hores de la matinada i en tres moments puntuals de tardes diferents","icon":"fa-thermometer-empty"},
                    {"text":"Hi ha hagut 3 pics en la humitat del sòl durant aquests dies","icon":"fa-arrow-circle-up"},
                    {"text":"Hi ha hagut 1 davallada en la humitat del sòl durant aquests dies","icon":"fa-water"},
                    {"text":"La mesura màxima pel CO2 ha estat 975 ppm","icon":"fa-exclamation-circle"},
                    {"text":"La mesura mínima pel CO2 ha estat 222 ppm","icon":"fa-exclamation-circle"},
                    {"text":"Hi ha hagut 2 davallades petites en el CO2","icon":"fa-arrow-circle-down"},
                    {"text":"La planta només ha passat set un dia d’aquesta setmana","icon":"fa-water"},
                    {"text":"Cada dia hi ha hagut 1 pic en la il·luminació entre les 16:30h i les 18:00h de la tarda","icon":"fa-calendar"},
                    {"text":"Hi ha 3 pics en la humitat del sòl que coincideixen amb 3 davallades en la humitat ambiental","icon":"fa-arrows-alt-v"},
                    {"text":"La il·luminació màxima ha estat de 127 lux","icon":"fa-sun"},
                    {"text":"La humitat màxima ha estat d’un 26%","icon":"fa-arrow-circle-up"}]

advice_plantHistory = [{"text":"La temperatura ha augmentat un 8% respecte la setmana passada; si has canviat la ubicació de la planta, pot haver canviat la temperatura","icon":"fa-thermometer-three-quarters"},
                    {"text":"La temperatura màxima ha estat 25.8ºC; el rang adequat per a la teva planta és d’entre 15ºC i 25ºC","icon":"fa-thermometer-full"},
                    {"text":"S’han recollit dades cada 35 minuts; comprova el temps exacte que ha passat comparant les hores de dos punts consecutius en el gràfic","icon":"fa-clock"},
                    {"text":"La temperatura màxima ha estat a les 17:20h; mira si coincideix amb les hores on li toca més el sol. Vigila que la planta tingui una temperatura i il·luminació adequada.","icon":"fa-clock"},
                    {"text":"Les temperatures mínimes han estat durant les hores de la matinada i en tres moments puntuals de tardes diferents; la temperatura no sol baixar tant durant les tardes, comprova si té relació amb alguna altra mesura que hagi pogut provocar aquestes davallades en la temperatura, com per exemple amb l’aigua del reg (humitat del sòl).","icon":"fa-thermometer-empty"},
                    {"text":"Hi ha hagut 3 pics en la humitat del sòl durant aquests dies; és quan has regat la planta? La humitat del sòl augmenta amb l’aigua. Fixa’t en les hores per saber quins dies són.","icon":"fa-arrow-circle-up"},
                    {"text":"Hi ha hagut 1 davallada en la humitat del sòl durant aquests dies; això vol dir que la terra està més seca. T’has oblidat de regar la planta? Sembla que la planta ha passat set i això contribueix a un mal estat.","icon":"fa-water"},
                    {"text":"La mesura màxima pel CO2 ha estat 975 ppm; tot i que les plantes necessitin el CO2 per a la fotosíntesi, un excés de CO2 també pot ser perjudicial.","icon":"fa-exclamation-circle"},
                    {"text":"La mesura mínima pel CO2 ha estat 222 ppm; hi ha hagut prou ventilació a l’aula? La planta necessita ventilació i aire nou.","icon":"fa-exclamation-circle"},
                    {"text":"Hi ha hagut 2 davallades petites en el CO2; mira si coincideixen amb 2 pics en la humitat del sòl","icon":"fa-arrow-circle-down"},
                    {"text":"La planta només ha passat set un dia d’aquesta setmana; si la humitat del sòl ha baixat notablement, és que no hi ha hagut prou aigua i la terra s’ha assecat","icon":"fa-water"},
                    {"text":"Cada dia hi ha hagut 1 pic en la il·luminació entre les 16:30h i les 18:00h de la tarda; comprova si coincideixen amb els pics en la temperatura","icon":"fa-calendar"},
                    {"text":"Hi ha 3 pics en la humitat del sòl que coincideixen amb 3 davallades en la humitat ambiental; quan reguem la planta, la humitat del sòl augmenta amb l’aigua, i disminueix la humitat en l’aire del voltant de la planta.","icon":"fa-arrows-alt-v"},
                    {"text":"La il·luminació màxima ha estat de 127 lux; assegura’t que la llum solar no sigui massa directa i faci malbé les fulles","icon":"fa-sun"},
                    {"text":"La humitat màxima ha estat d’un 26%; la teva planta requereix molta humitat ambiental","icon":"fa-arrow-circle-up"}]

alerts_singleMeasure = [{"text":"Els termòmetres mostren els valors per cada mesura recollida","icon":"fa-binoculars"},
                    {"text":"Els valors màxims i mínims de cada termòmetre poden ser diferents","icon":"fa-exclamation-circle"},
                    {"text":"Es mostren les mesures per un dia i hora concrets","icon":"fa-clock"},
                    {"text":"La mesura pel CO2 està en vermell","icon":"fa-exclamation-circle"},
                    {"text":"La majoria de mesures estan en verd","icon":"fa-check-circle"}]

advice_singleMeasure = [{"text":"Els termòmetres mostren els valors per cada mesura recollida, i corresponen als punts del gràfic","icon":"fa-binoculars"},
                    {"text":"Els valors màxims i mínims de cada termòmetre poden ser diferents; cada mesura té el seu interval i les seves unitats, fixa-t’hi i tingueu-ho en compte a l’hora de comparar visualment","icon":"fa-exclamation-circle"},
                    {"text":"Es mostren les mesures per un dia i hora concrets; comprova si hi ha alguna observació que indiqui si has regat la planta, ventilat la classe, si la planta ha florit, etc. per entendre millor les mesures","icon":"fa-clock"},
                    {"text":"La mesura pel CO2 està en vermell, recorda que no necessàriament la planta està en perill; pots ajustar els límits superiors i inferiors per la teva planta a la configuració","icon":"fa-exclamation-circle"},
                    {"text":"La majoria de mesures estan en verd. Recorda que això no indica que l’estat de la planta sigui bo; comprova primer que els límits estiguin ben configurats i, si ja estan bé, continua cuidant de la teva planta","icon":"fa-check-circle"}]