version: '2'
services:
  mysql:
    image: mysql:8.0
    container_name: docker-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: Teaspils_DB
      MYSQL_USER: admin
      MYSQL_PASSWORD: TIDE2021
      MYSQL_ROOT_PASSWORD: TEASPILS2021@
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "mysql-data:/var/lib/mysql"

  webserver:
    image: phpstorm/php-apache:7.4-xdebug2.9
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

volumes:
  mysql-data:
