# Generated by Django 3.2.8 on 2022-04-21 22:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('secret_word', models.CharField(max_length=12)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaspils_backend.center')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('data_source', models.CharField(default='no-source', max_length=512)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teaspils_backend.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaspils_backend.course')),
            ],
        ),
        migrations.CreateModel(
            name='PlantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_temperature', models.IntegerField(default=0)),
                ('high_temperature', models.IntegerField(default=0)),
                ('low_noise', models.IntegerField(default=0)),
                ('high_noise', models.IntegerField(default=0)),
                ('low_co2', models.IntegerField(default=0)),
                ('high_co2', models.IntegerField(default=0)),
                ('low_humidity', models.IntegerField(default=0)),
                ('high_humidity', models.IntegerField(default=0)),
                ('low_light', models.IntegerField(default=0)),
                ('high_light', models.IntegerField(default=0)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaspils_backend.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=50)),
                ('text', models.TextField(max_length=1200)),
                ('filePath', models.FilePathField(path='media©©©/')),
                ('image', models.ImageField(upload_to='obs_images/')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaspils_backend.plant')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=50)),
                ('text', models.TextField(max_length=1200)),
                ('filePath', models.FilePathField(path='media/')),
                ('image', models.ImageField(upload_to='obs_images/')),
                ('timestamp', models.DateTimeField()),
                ('measure_timestamp', models.DateTimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaspils_backend.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0, null=True)),
                ('noise', models.FloatField(default=0.0, null=True)),
                ('timestamp', models.TimeField(default=datetime.datetime.now)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaspils_backend.plant')),
            ],
        ),
    ]
