# Generated by Django 3.2.8 on 2022-04-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaspils_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measureobservation',
            name='filePath',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='filePath',
        ),
    ]
