# Generated by Django 3.2.8 on 2022-04-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaspils_backend', '0002_remove_measureobservation_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='filePath',
        ),
    ]
