# Generated by Django 4.0.4 on 2022-05-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaspils_backend', '0003_remove_observation_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantsettings',
            name='high_soilHum',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='plantsettings',
            name='high_soilTemp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='plantsettings',
            name='low_soilHum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plantsettings',
            name='low_soilTemp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plantsettings',
            name='high_co2',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='plantsettings',
            name='high_humidity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='plantsettings',
            name='high_light',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='plantsettings',
            name='high_temperature',
            field=models.IntegerField(default=100),
        ),
    ]
